// tag::FEEDBACK[]
:filename: 01-basics/03-prerequisites-for-this-training.adoc
include::../config/_feedback.adoc[]
// end::FEEDBACK[]

// tag::DE[]
=== Voraussetzungen für das Modul {curriculum-short}

Teilnehmerinnen und Teilnehmer **sollten** folgende Kenntnisse und/oder Erfahrung mitbringen:

- Grundlagen der Beschreibung von Architekturen mit Hilfe verschiedener Sichten, übergreifender Konzepte, Entwurfsentscheidungen, Randbedingungen etc., wie es im CPSA- F (Foundation Level) vermittelt wird.
- Erfahrung mit der Implementierung und Architektur in agilen Projekten.
- Erfahrungen aus der Entwicklung und Architektur klassischer Systeme mit den typischen
Herausforderungen.

**Hilfreich** für das Verständnis einiger Konzepte sind darüber hinaus:

- Verteilte Systeme
  * Probleme und Herausforderungen bei der Implementerung verteilter Systeme o Typische verteilte Algorithmen
  * Internet-Protokolle
- Kenntnisse über Modularisierungen o Fachliche Modularisierung
  * Technische Umsetzungen wie Pakete oder Bibiliotheken · Klassische Betriebs- und Deployment-Prozesse

// end::DE[]

// tag::EN[]
=== Prerequisites for the module {curriculum-short}

Participants **should** have the following prerequisite knowledge:

- Prerequisite 1
- Prerequisite 2, etc.

Knowledge in the following areas may be **helpful** for understanding some concepts:

- Area 1:
  * Knowledge 1
  * Experience 2
  * Knowledge 3
  * Experience 4
  * Understanding 5
// end::EN[]

// tag::REMARK[]
[NOTE]
====
Kenntnisgruppen sowie Voraussetzungen bitte entsprechend ausformulieren!
====
// end::REMARK[]
